Add utf-8 encoding for reading test.txt
When I ran `test.py` I got this error :
```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 255: character maps to <undefined>
```
And it is caused by using non-ASCII characters like Persian characters